
USE DW_COMERCIAL
GO

/*########################################################*/
/*      Alter para las FK de la tabla FACT_VENTAS		  */
/*########################################################*/

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (PRODUCTO_KEY)
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_PRODUCTO] (PRODUCTO_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_CATEGORIA] (CATEGORIA_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_CLIENTE] (CLIENTE_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_PAIS FOREIGN KEY (PAIS_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_PAIS] (PAIS_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_VENDEDOR FOREIGN KEY (VENDEDOR_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_VENDEDOR] (VENDEDOR_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_SUCURSAL FOREIGN KEY (SUCURSAL_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_SUCURSAL] (SUCURSAL_KEY);

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS 
	ADD	CONSTRAINT FK_TIEMPO FOREIGN KEY (TIEMPO_KEY) 
		REFERENCES [DW_COMERCIAL].[DBO].[DIM_TIEMPO] (TIEMPO_KEY);
