
USE DW_COMERCIAL
GO

/*##############################################################*/
/*					CREACION TABLAS STG							*/
/*		Utilice NVARCHAR en lugar de VARCHAR para evitar        */
/*		  inconvenientes con los caracteres especiales			*/
/*						(acentos/�)								*/
/*##############################################################*/

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_PRODUCTO
		(COD_PRODUCTO NVARCHAR(500),
		DESC_PRODUCTO NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_CATEGORIA
		(COD_CATEGORIA NVARCHAR(500),
		DESC_CATEGORIA NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_CLIENTE
		(COD_CLIENTE NVARCHAR(500),
		DESC_CLIENTE NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_PAIS
		(COD_PAIS NVARCHAR(500),
		DESC_PAIS NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_VENDEDOR
		(COD_VENDEDOR NVARCHAR(500),
		DESC_VENDEDOR NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_DIM_SUCURSAL
		(COD_SUCURSAL NVARCHAR(500),
		DESC_SUCURSAL NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.STG_FACT_VENTAS
		(COD_PRODUCTO NVARCHAR(500),
		COD_CATEGORIA NVARCHAR(500),
		COD_CLIENTE NVARCHAR(500),
		COD_PAIS NVARCHAR(500),
		COD_VENDEDOR NVARCHAR(500),
		COD_SUCURSAL NVARCHAR(500),
		FECHA NVARCHAR(500),
		CANTIDAD_VENDIDA NVARCHAR(500),
		MONTO_VENDIDO NVARCHAR(500),
		PRECIO NVARCHAR(500),
		COMISION_COMERCIAL NVARCHAR(500))
;
