USE DW_COMERCIAL
GO

/*##############################################################*/
/*			       CREACION TABLAS FINALES                      */
/*##############################################################*/

CREATE TABLE [DW_COMERCIAL].DBO.DIM_PRODUCTO
		(PRODUCTO_KEY INTEGER IDENTITY (1,1),
		COD_PRODUCTO NVARCHAR(500),
		DESC_PRODUCTO NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_PRODUCTO PRIMARY KEY (PRODUCTO_KEY )
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_CATEGORIA
		(CATEGORIA_KEY INTEGER IDENTITY (1,1),
		COD_CATEGORIA NVARCHAR(500),
		DESC_CATEGORIA NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATEGORIA_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_CLIENTE
		(CLIENTE_KEY INTEGER IDENTITY(1,1),
		COD_CLIENTE NVARCHAR(500),
		NOMBRE NVARCHAR(500),
		APELLIDO NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_PAIS
		(PAIS_KEY INTEGER IDENTITY(1,1),
		COD_PAIS NVARCHAR(3),
		DESC_PAIS NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_PAIS PRIMARY KEY (PAIS_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_VENDEDOR
		(VENDEDOR_KEY INTEGER IDENTITY(1,1),
		COD_VENDEDOR NVARCHAR(500),
		NOMBRE NVARCHAR(500),
		APELLIDO NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_VENDEDOR PRIMARY KEY (VENDEDOR_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_SUCURSAL
		(SUCURSAL_KEY INTEGER IDENTITY(1,1),
		COD_SUCURSAL NVARCHAR(500),
		DESC_SUCURSAL NVARCHAR(500),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		FECHA_UPDATE DATETIME,
		USUARIO_UPDATE NVARCHAR(500),
		CONSTRAINT PK_SUCURSAL PRIMARY KEY (SUCURSAL_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.DIM_TIEMPO
		(TIEMPO_KEY SMALLDATETIME,
		ANIO INTEGER,
		MES_NRO INTEGER,
		MES_NOMBRE NVARCHAR(15),
		SEMESTRE INTEGER,
		TRIMESTRE INTEGER,
		SEMANA_ANIO INTEGER,
		SEMANA_NRO_MES INTEGER,
		DIA INTEGER,
		DIA_NOMBRE NVARCHAR(20),
		DIA_SEMANA_NRO INTEGER,
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		CONSTRAINT PK_TIEMPO PRIMARY KEY (TIEMPO_KEY)
		)
;

CREATE TABLE [DW_COMERCIAL].DBO.FACT_VENTAS
		(PRODUCTO_KEY INTEGER,
		CATEGORIA_KEY INTEGER,
		CLIENTE_KEY INTEGER,
		PAIS_KEY INTEGER,
		VENDEDOR_KEY INTEGER,
		SUCURSAL_KEY INTEGER,
		TIEMPO_KEY SMALLDATETIME,
		CANTIDAD_VENDIDA DECIMAL(18,2),
		MONTO_VENDIDO DECIMAL(18,2),
		PRECIO DECIMAL(18,2),
		COMISION_COMERCIAL DECIMAL(18,2),
		FECHA_ALTA DATETIME,
		USUARIO_ALTA NVARCHAR(500),
		CONSTRAINT UNQ_FACT_VENTAS 
				UNIQUE (PRODUCTO_KEY, CATEGORIA_KEY, CLIENTE_KEY, PAIS_KEY, VENDEDOR_KEY, SUCURSAL_KEY, TIEMPO_KEY)
		)
;