USE DW_COMERCIAL
GO

/*##############################################################*/
/*			        CREACION TABLAS INT                         */
/*##############################################################*/

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_PRODUCTO
		(COD_PRODUCTO NVARCHAR(500),
		DESC_PRODUCTO NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_CATEGORIA
		(COD_CATEGORIA NVARCHAR(500),
		DESC_CATEGORIA NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_CLIENTE
		(COD_CLIENTE NVARCHAR(500),
		NOMBRE NVARCHAR(500),
		APELLIDO NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_PAIS
		(COD_PAIS NVARCHAR(3),
		DESC_PAIS NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_VENDEDOR
		(COD_VENDEDOR NVARCHAR(500),
		NOMBRE NVARCHAR(500),
		APELLIDO NVARCHAR(500))
;

CREATE TABLE [DW_COMERCIAL].DBO.INT_DIM_SUCURSAL
		(COD_SUCURSAL NVARCHAR(500),
		DESC_SUCURSAL NVARCHAR(500))
;
CREATE TABLE [DW_COMERCIAL].DBO.INT_FACT_VENTAS
		(COD_PRODUCTO NVARCHAR(500),
		COD_CATEGORIA NVARCHAR(500),
		COD_CLIENTE NVARCHAR(500),
		COD_PAIS NVARCHAR(500),
		COD_VENDEDOR NVARCHAR(500),
		COD_SUCURSAL NVARCHAR(500),
		FECHA SMALLDATETIME,
		CANTIDAD_VENDIDA DECIMAL(18,2),
		MONTO_VENDIDO DECIMAL(18,2),
		PRECIO DECIMAL(18,2),
		COMISION_COMERCIAL DECIMAL(18,2))
;