
USE DW_COMERCIAL
GO

/*################################################################*/
/*			   STORE PROCEDURE CARGA DE STG A INT                 */
/*################################################################*/

-- SP para agregar datos de SGT_DIM_CATEGORIA a INT_DIM_CATEGORIA
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_CATEGORIA
AS
BEGIN

	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE [DW_COMERCIAL].DBO.INT_DIM_CATEGORIA;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_CATEGORIA 
		([COD_CATEGORIA],
		[DESC_CATEGORIA])
	SELECT [COD_CATEGORIA],
		[DESC_CATEGORIA]
	FROM [DW_COMERCIAL].DBO.STG_DIM_CATEGORIA
END
GO

-- SP para agregar datos de SGT_DIM_CLIENTE a INT_DIM_CLIENTE
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_CLIENTE
AS
BEGIN
	
	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE [DW_COMERCIAL].DBO.INT_DIM_CLIENTE;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_CLIENTE
		([COD_CLIENTE],
		[NOMBRE],
		[APELLIDO])
	SELECT  COD_CLIENTE,
	--Los clientes los dividimos en 1 o 2 apellidos
		CASE LEN(DESC_CLIENTE)-LEN(REPLACE(DESC_CLIENTE, ' ','')) 
			WHEN 2 THEN PARSENAME(REPLACE(DESC_CLIENTE, ' ','.'), 3)
			WHEN 1 THEN PARSENAME(REPLACE(DESC_CLIENTE, ' ','.'), 2)
			END NOMBRE,
		CASE LEN(DESC_CLIENTE)-LEN(REPLACE(DESC_CLIENTE, ' ','')) 
			WHEN 2 THEN CONCAT(PARSENAME(REPLACE(DESC_CLIENTE, ' ','.'), 2), ' ' ,PARSENAME(REPLACE(DESC_CLIENTE, ' ','.'), 1))
			WHEN 1 THEN PARSENAME(REPLACE(DESC_CLIENTE, ' ','.'), 1)
			END APELLIDO
	FROM [DW_COMERCIAL].DBO.STG_DIM_CLIENTE
END
GO

-- SP para agregar datos de SGT_DIM_PAIS a INT_DIM_PAIS
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_PAIS
AS
BEGIN
	
	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE [DW_COMERCIAL].DBO.INT_DIM_PAIS;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_PAIS
			( [COD_PAIS],
			[DESC_PAIS]	)
	SELECT [COD_PAIS],
			[DESC_PAIS]
	FROM [DW_COMERCIAL].DBO.STG_DIM_PAIS
END
GO

-- SP para agregar datos de SGT_DIM_PRODUCTO a INT_DIM_PRODUCTO
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_PRODUCTO
AS
BEGIN

	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE  [DW_COMERCIAL].DBO.INT_DIM_PRODUCTO;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_PRODUCTO
			( [COD_PRODUCTO],
			[DESC_PRODUCTO]	)
	SELECT [COD_PRODUCTO],
			[DESC_PRODUCTO]
	FROM [DW_COMERCIAL].DBO.STG_DIM_PRODUCTO
END
GO

-- SP para agregar datos de SGT_DIM_SUCURSAL a INT_DIM_SUCURSAL
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_SUCURSAL
AS
BEGIN

	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE  [DW_COMERCIAL].DBO.INT_DIM_SUCURSAL;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_SUCURSAL
			([COD_SUCURSAL],
			[DESC_SUCURSAL])
	SELECT [COD_SUCURSAL],
			[DESC_SUCURSAL]
	FROM [DW_COMERCIAL].DBO.STG_DIM_SUCURSAL
END
GO

-- SP para agregar datos de SGT_DIM_VENDEDOR a INT_DIM_VENDEDOR
CREATE PROCEDURE DBO.SP_CARGA_INT_DIM_VENDEDOR
AS
BEGIN
	
	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE  [DW_COMERCIAL].DBO.INT_DIM_VENDEDOR;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_DIM_VENDEDOR
			([COD_VENDEDOR],
			[NOMBRE],
			[APELLIDO])
	SELECT 	 
		[COD_VENDEDOR], 
		--  Los vendedores dividimos en 1 o 2 nombres
		 CASE LEN(DESC_VENDEDOR)-LEN(REPLACE(DESC_VENDEDOR, ' ','')) 
			WHEN 2 THEN CONCAT(PARSENAME(REPLACE(DESC_VENDEDOR, ' ','.'), 3), ' ', PARSENAME(REPLACE(DESC_VENDEDOR, ' ','.'), 2))
			WHEN 1 THEN PARSENAME(REPLACE(DESC_VENDEDOR, ' ','.'), 2)
			END NOMBRE,
		PARSENAME(REPLACE(DESC_VENDEDOR, ' ','.'), 1) APELLIDO
		FROM [DW_COMERCIAL].DBO.STG_DIM_VENDEDOR;
END
GO

-- SP para agregar datos de SGT_FACT_VENTAS a INT_FACT_VENTAS
CREATE PROCEDURE DBO.SP_CARGA_INT_FACT_VENTAS
AS
BEGIN

	-- Borrar datos existentes en la tabla
	TRUNCATE TABLE  [DW_COMERCIAL].DBO.INT_FACT_VENTAS;

	-- Insertar los datos de la tabla STG
	INSERT INTO [DW_COMERCIAL].DBO.INT_FACT_VENTAS
			([COD_PRODUCTO],
			[COD_CATEGORIA],
			[COD_CLIENTE],
			[COD_PAIS],
			[COD_VENDEDOR],
			[COD_SUCURSAL],
			[FECHA],
			[CANTIDAD_VENDIDA],
			[MONTO_VENDIDO],
			[PRECIO],
			[COMISION_COMERCIAL])
	SELECT 
		[COD_PRODUCTO],
		[COD_CATEGORIA],
		[COD_CLIENTE],
		[COD_PAIS],
		[COD_VENDEDOR],
		[COD_SUCURSAL],

		--La fecha de import� como dias, por lo que primero lo paso a decimal y luego a formato fecha fecha
		CAST(CAST([FECHA] AS DECIMAL(18,2)) AS smalldatetime) [FECHA],

		-- El resto de atributos, reemplazo la coma por un punto, para realizar el casteo a decimal
		CAST(REPLACE([CANTIDAD_VENDIDA],',','.') AS DECIMAL(18,2)),
		CAST(REPLACE([MONTO_VENDIDO],',','.') AS DECIMAL(18,2)),
		CAST(REPLACE([PRECIO],',','.') AS DECIMAL(18,2)),
		CAST(REPLACE([COMISION_COMERCIAL],',','.') AS DECIMAL(18,2))
	FROM [DW_COMERCIAL].DBO.STG_FACT_VENTAS;
END
GO
